# Use a specific Python version
FROM mcr.microsoft.com/devcontainers/python:3.11

# [Optional] Install additional OS packages.
#RUN apt-get update && apt-get install -y <additional-packages>

# [Optional] Install Python packages globally to the environment.
RUN pip install requirements.txt
